import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { FaSchool, FaUserGraduate, FaBuilding, FaChalkboardTeacher } from 'react-icons/fa';
import { Navigation } from  '../components/navigation';
import { Toaster } from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sophos University',
  description: 'Generated by create next app',
}

const links = [
  { href: '/faculty', label: 'Faculties', icon: <FaBuilding/> },
  { href: '/course', label: 'Courses', icon: <FaSchool/> },
  { href: '/student', label: 'Students', icon: <FaUserGraduate/> },
  { href: '/professor', label: 'Professors',  icon: <FaChalkboardTeacher/> },
  { href: '/semester', label: 'Semesters',  icon: <FaChalkboardTeacher/> },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex'>
          <Toaster/>
          <Navigation links={links}/>
          {children}
        </div>
      </body>
    </html>
  )
}
